# ??
server:
  port: 9001

# sa-token??
sa-token:
  # SSO-????
  sso:
    # SSO-Server? ??????
    auth-url: http://localhost:9000/sso/auth
    # ??Http????ticket
    is-http: true
    # SSO-Server? ticket????
    check-ticket-url: http://localhost:9000/sso/checkTicket
    # ????????
    is-slo: true
    # ??????
    slo-url: http://localhost:9000/sso/logout
    # ??????
    secretkey: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor
    # SSO-Server? ??userinfo??
    userinfo-url: http://localhost:9000/sso/userinfo

spring:
  # ?? Redis ?? ????SSO-Server??????Redis?
  redis:
    # Redis?????
    database: 2
    # Redis?????
    host: 127.0.0.1
    # Redis???????
    port: 6379
    # Redis?????????????
    password:
    # ??????
    timeout: 10s
    lettuce:
      pool:
        # ????????
        max-active: 200
        # ???????????????????????
        max-wait: -1ms
        # ???????????
        max-idle: 10
        # ???????????
        min-idle: 0
