# ??
server:
  port: 9000

# Sa-Token ??
sa-token:
  # -------------- SSO-???????  (?????????)
  # cookie:
  # ??Cookie???
  # domain: stp.com

  # ------- SSO-???????
  sso:
    # Ticket??? (??: ?)??????
    ticket-timeout: 300
    # ???????????
    allow-url: "*"
    # ??????????
    is-slo: true

    # ------- SSO-??????? ???????SSO????? is-slo=true ???? -------
    # ???????
    isHttp: true
    # ?????????SSO???????????
    secretkey: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor
    # ---- ????????????? Sa-Token ??http??????????????

spring:
  # Redis?? ?SSO?????????Redis??????
  redis:
    # Redis?????????0?
    database: 1
    # Redis?????
    host: 127.0.0.1
    # Redis???????
    port: 6379
    # Redis?????????????
    password:
